# Generated by Django 4.0.3 on 2022-03-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
